### ISSUE TITLE
Error import library

### ISSUE THREAD

**Issue by dacontor** [ekreutz/react-native-barcode-scanner-google#10]
when add library, react native show red screen with the following message:

"undefined is not an object (evaluating '_react2.PropTypes.func')" 

any idea??

regards

**Comment by ekreutz** [comment]
Try to pull the most recent commit, and not v1.2.0

**Comment by ekreutz** [comment]
Something like this:
```
npm install git+https://github.com/ekreutz/react-native-barcode-scanner-google.git#ece3e0a --save
```

Or similar... Latest commit should solve this!

**Comment by dacontor** [comment]
Great!! 
it worked

Thanks!!
