### ISSUE TITLE
Pause camera

### ISSUE THREAD

**Issue by giorgiootto** [ekreutz/react-native-barcode-scanner-google#15]
Hi ,

Could pass a example to pause camera????

**Comment by romanenko** [comment]
Hello, @giorgiootto.

I guess, you just need to follow instructions https://github.com/ekreutz/react-native-barcode-scanner-google#utility-functions-resumescanner-and-pausescanner-function 

Just include `pauseScanner()` functions from 'react-native-barcode-scanner-google' module and use it in your component method.

**Comment by giorgiootto** [comment]
Thanks.
