### ISSUE TITLE
How to close the camera after reading the barcode in android?

### ISSUE THREAD

**Issue by Aravindhan12** [ekreutz/react-native-barcode-scanner-google#16]
I was able to read the barcode successfully. But how can I close the camera after reading the barcode ?

**Comment by romanenko** [comment]
I'd suggest you to use some kind of navigation library, like, for example [ReactNavigation](https://github.com/react-navigation/react-navigation). Use scanner on one screen and just navigate away from it, by pushing new screen to the stack.

Simpler approach would be to keep state in component, where you intent to use this scanner. And, when `onBarcodeRead` you should `pauseScanner` (See instructions [here](https://github.com/ekreutz/react-native-barcode-scanner-google#utility-functions-resumescanner-and-pausescanner-function)) and `setState()` to some value, to render something, for example, on top of everything

**Comment by 3lhagvaasuren** [comment]
@Aravindhan12 can you post the implementation? That could help me. My code is not working. And can you please post your package.JSON?

**Comment by ekreutz** [comment]
@romanenko thanks for the answer.
In short, use the following approaches:
1. Navigate away from the scanner view
2. [advanced] Manage the scanning state using `pauseScanner()` and `startScanner()`
