### ISSUE TITLE
Torch is Not working , i followed the advanced example at it is ? react native: 0.55.4, react: 16.3.1

### ISSUE THREAD

**Issue by dileepbolisetti** [ekreutz/react-native-barcode-scanner-google#30]

**Comment by jqn** [comment]
@dileepbolisetti you have to toggle torchmode to on via a user interaction. Torchmode should be initialized to off the toggle to on.

**Comment by neonrazor** [comment]
Can you give me an example of how to do this, I have set it using a state var but it still doesnt work on my honor P9 lite, the torch just doesnt work.  I also noticed the even with the type set to QR the camera still reads barcode, its almost as if its ignoring the props.
