### ISSUE TITLE
v1.3.0 can't install

### ISSUE THREAD

**Issue by kryst4l** [ekreutz/react-native-barcode-scanner-google#8]
$ npm install git+https://github.com/ekreutz/react-native-barcode-scanner-google.git#v1.3.0 --save
npm ERR! git rev-list -n1 v1.3.0: fatal: ambiguous argument 'v1.3.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 v1.3.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 v1.3.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 v1.3.0:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+https://github.com/ekreutz/react-native-bar
code-scanner-google.git#v1.3.0" "--save"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 v1.3.0
npm ERR! fatal: ambiguous argument 'v1.3.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:

**Comment by kruyvanna** [comment]
There is no v1.3.0 yet.

Latest is v1.2.0
