### ISSUE TITLE
camera not shown but a black screen rendered

### ISSUE THREAD

**Issue by icesyc** [ekreutz/react-native-barcode-scanner-google#9]
XiaoMi  MI 4LTE
android version 4.4

**Comment by emrahtoy** [comment]
Same on LG4 and Genymotion Virtual Devices

**Comment by kruyvanna** [comment]
Hi check the fix here
https://github.com/ekreutz/react-native-barcode-scanner-google/pull/6/commits/df3ed0dfc2f4cfcee0957421d450deb3a04d52b7

**Comment by jjliyu** [comment]
I try  df3ed0d  but not work ,black screen  again

**Comment by kruyvanna** [comment]
try clearing cache. delete npm_modules and install again

**Comment by ekreutz** [comment]
This framework uses the Camera 2 API, which isn't available in versions of Android prior to 5.0 (API 21)
